/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminDockerRouteImport } from './routes/admin.docker'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDockerRoute = AdminDockerRouteImport.update({
  id: '/admin/docker',
  path: '/admin/docker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/docker': typeof AdminDockerRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/system': typeof AdminSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/docker': typeof AdminDockerRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/system': typeof AdminSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/docker': typeof AdminDockerRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/system': typeof AdminSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/docker'
    | '/admin/health'
    | '/admin/system'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin/docker' | '/admin/health' | '/admin/system'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/docker'
    | '/admin/health'
    | '/admin/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminDockerRoute: typeof AdminDockerRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminSystemRoute: typeof AdminSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/docker': {
      id: '/admin/docker'
      path: '/admin/docker'
      fullPath: '/admin/docker'
      preLoaderRoute: typeof AdminDockerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminDockerRoute: AdminDockerRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminSystemRoute: AdminSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
